import{verbById,type AudioMoodSample}from'../types/audiomood';
type Quality='HIGH'|'MEDIUM'|'LOW';
type Smoothed={low:number;mid:number;high:number;rms:number;centroid:number;flux:number;transient:number};
const TAU=Math.PI*2;
const seeded=(seed:number,n:number)=>{const x=Math.sin(seed*12.9898+n*78.233)*43758.5453;return x-Math.floor(x)};
export class SensoryVisualEngine{
 private smooth=new Map<string,Smoothed>();private quality:Quality='HIGH';private slowFrames=0;private offsets=new Map<string,Float32Array>();
 constructor(private ctx:CanvasRenderingContext2D){}
 setQuality(q:Quality){this.quality=q}
 reportFrame(ms:number){this.slowFrames=ms>22?this.slowFrames+1:Math.max(0,this.slowFrames-2);if(this.slowFrames>35){this.quality=this.quality==='HIGH'?'MEDIUM':'LOW';this.slowFrames=0}}
 render(samples:AudioMoodSample[],active:Set<string>,t:number,w:number,h:number){const x=this.ctx;x.globalCompositeOperation='source-over';x.globalAlpha=1;const bg=x.createRadialGradient(w*.5,h*.48,4,w*.5,h*.48,Math.max(w,h)*.72);bg.addColorStop(0,'#20283a');bg.addColorStop(.55,'#101722');bg.addColorStop(1,'#080c14');x.fillStyle=bg;x.fillRect(0,0,w,h);const shown=active.size?samples.filter(s=>active.has(s.id)):samples.slice(0,3);for(const s of shown)this.drawSample(s,t,w,h,active.size?1:.22)}
 private values(s:AudioMoodSample){const v=verbById(s.sensoryVerb),f=s.audioFeatures,target={...f,transient:f.transient??f.flux},old=this.smooth.get(s.id)??{...target};for(const k of Object.keys(old)as(keyof Smoothed)[]){const rate=target[k]>old[k]?v.attack:v.release;old[k]+=(target[k]-old[k])*rate}this.smooth.set(s.id,old);return old}
 private irregular(s:AudioMoodSample){let a=this.offsets.get(s.id);if(!a){a=new Float32Array(24);for(let i=0;i<a.length;i++)a[i]=seeded(s.visualSeed,i)*2-1;this.offsets.set(s.id,a)}return a}
 private blob(cx:number,cy:number,r:number,phase:number,noise:Float32Array,stretch=1){const x=this.ctx,n=noise.length;x.beginPath();for(let i=0;i<=n;i++){const a=i/n*TAU,j=i%n,rr=r*(1+noise[j]*.09+Math.sin(phase+i*.7)*.035),px=cx+Math.cos(a)*rr*stretch,py=cy+Math.sin(a)*rr;if(i===0)x.moveTo(px,py);else x.lineTo(px,py)}x.closePath()}
 private wash(cx:number,cy:number,r:number,phase:number,s:AudioMoodSample,alpha:number,stretch=1){const x=this.ctx,v=verbById(s.sensoryVerb),noise=this.irregular(s);for(let layer=0;layer<(this.quality==='LOW'?2:3);layer++){this.blob(cx,cy,r*(1+layer*.12),phase+layer,noise,stretch);x.fillStyle=layer===0?v.primary:v.secondary;x.globalAlpha=alpha/(layer+1);x.fill();if(layer===0){x.strokeStyle=v.accent;x.globalAlpha=alpha*.72;x.lineWidth=1.2;x.stroke()}}}
 private filament(cx:number,cy:number,r:number,a:number,bend:number,color:string,alpha:number){const x=this.ctx;x.beginPath();x.moveTo(cx,cy);x.bezierCurveTo(cx+Math.cos(a+.5)*r*.35,cy+Math.sin(a+.5)*r*.35,cx+Math.cos(a-bend)*r*.72,cy+Math.sin(a-bend)*r*.72,cx+Math.cos(a)*r,cy+Math.sin(a)*r);x.strokeStyle=color;x.globalAlpha=alpha;x.lineWidth=.7;x.stroke()}
 private drawSample(s:AudioMoodSample,t:number,w:number,h:number,presence:number){const x=this.ctx,f=this.values(s),v=verbById(s.sensoryVerb),seed=s.visualSeed,cx=w*(.5+(seeded(seed,2)-.5)*.24),cy=h*(.5+(seeded(seed,3)-.5)*.18),base=Math.min(w,h)*(.13+f.low*.1),phase=t+seed; x.globalCompositeOperation='screen';
  if(v.id==='berce'){const sway=Math.sin(phase*.42)*base*(.12+f.low*.2);this.wash(cx+sway,cy,base*(1+Math.sin(phase*.65)*.08),phase,s,presence*(.2+f.rms*.28),1.45+f.mid*.35);for(let i=0;i<8;i++)this.filament(cx+sway,cy,base*1.8,i/8*TAU+Math.sin(phase*.25)*.12,f.mid*.5,v.accent,presence*.16)}
  if(v.id==='petille'){const count=this.quality==='LOW'?5:9;this.wash(cx,cy,base*.72,phase,s,presence*.2,1);for(let i=0;i<count;i++){const a=i/count*TAU+seeded(seed,i),r=base*(.65+seeded(seed,i+20)*1.15),pulse=.55+.45*Math.sin(phase*(1.5+f.flux)+i);this.wash(cx+Math.cos(a)*r,cy+Math.sin(a)*r,4+(f.high*9+seeded(seed,i)*5)*pulse,phase+i,s,presence*.32);this.filament(cx,cy,r,a,f.mid,v.accent,presence*.22)}}
  if(v.id==='tourne'){const count=this.quality==='LOW'?4:7;for(let i=0;i<count;i++){const a=i/count*TAU+phase*(.12+f.rms*.18)*(i%2?.8:1),r=base*(.6+i*.22+f.low*.7),px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r*.65;this.filament(cx,cy,r*1.35,a,f.mid*.8,v.secondary,presence*.3);this.wash(px,py,base*.22,phase+i,s,presence*.25,1.8)}}
  if(v.id==='secoue'){const burst=(.25+.75*Math.pow((Math.sin(phase*(.7+f.transient))+1)/2,4)),r=base*(.7+burst*(1+f.low));this.wash(cx,cy,r*.55,phase,s,presence*.34);for(let i=0;i<(this.quality==='LOW'?7:13);i++){const a=i/13*TAU+seeded(seed,i)*.3;this.filament(cx,cy,r*(.8+seeded(seed,i+4)),a,f.mid*.7,v.accent,presence*(.12+burst*.3))}}
  if(v.id==='frissonne'){const count=this.quality==='LOW'?7:14;for(let i=0;i<count;i++){const a=-Math.PI*.15+i/(count-1)*Math.PI*1.3,r=base*(1.1+seeded(seed,i)*.7),micro=Math.sin(phase*(4+f.high*5)+i)*(.03+f.high*.09);this.filament(cx-base*.2,cy+Math.sin(i)*5,r,a+micro,f.mid*.55,v.primary,presence*.3)}}
  if(v.id==='enveloppe'){const count=this.quality==='LOW'?3:5;for(let i=0;i<count;i++){const a=phase*.08+i/count*TAU,open=1+f.low*.4+Math.sin(phase*.5+i)*.08;this.wash(cx+Math.cos(a)*base*.18,cy+Math.sin(a)*base*.12,base*open*(1-i*.08),phase+i,s,presence*(.12+i*.025),1.25+f.mid*.25)}}
  x.globalAlpha=1;x.globalCompositeOperation='source-over'}
}
