import { useEffect, useRef } from 'react'; import { FEELINGS, type Analysis, type Feeling, type FeelingMarker } from '../types/emosound';
type Burst={feeling:Feeling;born:number;lasting?:boolean};
export function SoundLandscape({analysis,markers,getTime,playing,onMarker,burstRef}:{analysis:Analysis;markers:FeelingMarker[];getTime:()=>number;playing:boolean;onMarker:(id:string)=>void;burstRef:React.MutableRefObject<Burst[]>}) {
 const canvas=useRef<HTMLCanvasElement>(null), markerRef=useRef(markers), playingRef=useRef(playing); markerRef.current=markers;playingRef.current=playing;
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d')!;let raf=0,last=getTime(),triggered=new Set<string>();const resize=()=>{const d=Math.min(2,devicePixelRatio);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();addEventListener('resize',resize);
 const draw=()=>{const w=c.clientWidth,h=c.clientHeight,now=performance.now(),t=getTime();ctx.clearRect(0,0,w,h);const present=w*.4,windowSec=Math.max(7,w/45),points=54;
  const grad=ctx.createLinearGradient(0,0,w,0);grad.addColorStop(0,'rgba(121,185,172,.08)');grad.addColorStop(.4,'rgba(255,239,207,.2)');grad.addColorStop(1,'rgba(121,185,172,.04)');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
  ctx.fillStyle='rgba(255,241,215,.045)';ctx.fillRect(present-16,0,32,h);ctx.strokeStyle='rgba(255,240,210,.36)';ctx.setLineDash([2,7]);ctx.beginPath();ctx.moveTo(present,12);ctx.lineTo(present,h-12);ctx.stroke();ctx.setLineDash([]);ctx.font='10px sans-serif';ctx.fillStyle='rgba(255,240,210,.52)';ctx.fillText('MAINTENANT',present-31,12);
  const colors=['#7fc9b6','#e1ae7c','#b4a4d7'];analysis.bands.forEach((band,b)=>{ctx.beginPath();for(let i=0;i<points;i++){const x=i/(points-1)*w,time=t+(x-present)/w*windowSec,idx=Math.max(0,Math.min(band.length-1,Math.floor(time/analysis.frameDuration))),energy=band[idx]||0,base=h*(.25+b*.25),wave=Math.sin(i*.46+time*(.75+b*.43))*energy*(18+b*3)+Math.sin(i*.16-time)*5;const y=base+wave;if(i===0)ctx.moveTo(x,y);else{const px=(i-.5)/(points-1)*w;ctx.quadraticCurveTo(px,base+Math.sin((i-.5)*.46+time*(.75+b*.43))*energy*(18+b*3),x,y)}}ctx.strokeStyle=colors[b];ctx.globalAlpha=.72;ctx.lineWidth=2;ctx.shadowColor=colors[b];ctx.shadowBlur=10;ctx.stroke();});ctx.globalAlpha=1;ctx.shadowBlur=0;
  for(const m of markerRef.current){const x=present+(m.time-t)/windowSec*w;if(x>-30&&x<w+30){if(playingRef.current&&last<m.time&&t>=m.time&&!triggered.has(m.id)){burstRef.current.push({feeling:m.feeling,born:now});triggered.add(m.id)}if(t<m.time-.2)triggered.delete(m.id);const f=FEELINGS.find(f=>f.id===m.feeling)!;ctx.font='20px sans-serif';ctx.textAlign='center';ctx.fillText(f.emoji,x,h*.51);ctx.fillStyle='rgba(255,245,225,.65)';ctx.beginPath();ctx.arc(x,h*.55,3,0,Math.PI*2);ctx.fill();if(m.duration>0){ctx.strokeStyle='rgba(255,245,225,.5)';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,h*.57);ctx.lineTo(x+m.duration/windowSec*w,h*.57);ctx.stroke()}}}
  burstRef.current=burstRef.current.filter(e=>now-e.born<700||e.lasting);for(const e of burstRef.current){const p=Math.min(1,(now-e.born)/600),r=12+p*45;ctx.strokeStyle='rgba(255,220,165,'+(1-p)+')';ctx.lineWidth=2;ctx.beginPath();if(e.feeling==='tension'){ctx.arc(present,h*.44,45-r*.6,0,Math.PI*2)}else if(e.feeling==='embrace'){ctx.arc(present,h*.44,r,-1.2,1.2);ctx.moveTo(present-r,h*.44);ctx.arc(present,h*.44,r,1.9,4.4)}else ctx.arc(present,h*.44,r,0,Math.PI*2);ctx.stroke();if(e.feeling==='spark')for(let i=0;i<6;i++){ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(present+Math.cos(i)*r,h*.44+Math.sin(i)*r,2,0,7);ctx.fill()}}
  last=t;raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize)}},[analysis,getTime,burstRef]);
 const click=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,t=getTime(),present=r.width*.4,windowSec=Math.max(7,r.width/45);let best:{id:string;d:number}|undefined;for(const m of markers){const mx=present+(m.time-t)/windowSec*r.width,d=Math.abs(mx-x);if(d<25&&(!best||d<best.d))best={id:m.id,d}}if(best)onMarker(best.id)};
 return <canvas ref={canvas} className="landscape" onPointerDown={click} aria-label="Paysage sonore animé"/>;
}
