import {useRef,useState} from 'react';
import type {Dispatch,PointerEvent as ReactPointerEvent,SetStateAction,WheelEvent} from 'react';
import type {Analysis,SensoryVerb,SoundBerry} from '../types/audiomood';
import {SENSORY_VERBS,verbById} from '../types/audiomood';
import type {AudioEngine} from '../audio/audioEngine';

type Phase='explore'|'discover'|'play'|'find';
type Camera={x:number;y:number;w:number;h:number};
const HOME={x:350,y:260,w:1500,h:980},WORLD={w:2200,h:1500};
const paths=[
 'M180 1260 C480 1110 480 780 780 735 S1120 700 1260 350','M380 1160 C600 940 820 1010 990 770 S1410 610 1900 430','M620 1270 C780 1020 1050 1110 1260 900 S1630 720 2040 790','M880 1250 C1000 980 980 650 790 390','M1110 1320 C1260 1070 1500 1110 1740 940 S1960 700 2080 580','M240 880 C600 770 700 490 1070 510 S1580 290 1870 230','M540 510 C860 660 1160 400 1460 560 S1840 520 2080 300'];

export function BushExperience({analysis,berries,setBerries,engine}:{analysis:Analysis;berries:SoundBerry[];setBerries:Dispatch<SetStateAction<SoundBerry[]>>;engine:AudioEngine}){
 const [phase,setPhase]=useState<Phase>('explore'),[camera,setCamera]=useState<Camera>(HOME),[focus,setFocus]=useState<string>(),[saved,setSaved]=useState(HOME),[drag,setDrag]=useState<{id:string;x:number;y:number}>(),[step,setStep]=useState(0),[playing,setPlaying]=useState<string>(),[tip,setTip]=useState(true);
 const gesture=useRef<{x:number;y:number;camera:Camera}|null>(null),picked=berries.filter(b=>b.state==='picked'),berry=berries.find(b=>b.id===focus);
 const update=(id:string,patch:Partial<SoundBerry>)=>setBerries(v=>v.map(b=>b.id===id?{...b,...patch}:b));
 const close=()=>{if(berry&&berry.state==='hidden')update(berry.id,{state:'seen'});setFocus(undefined);setCamera(saved)};
 const open=(b:SoundBerry)=>{if(b.state==='picked'||phase!=='explore')return;setSaved(camera);setFocus(b.id);setCamera({x:b.position.x-210,y:b.position.y-145,w:420,h:290});setTip(false)};
 const down=(e:ReactPointerEvent<SVGSVGElement>)=>{if(focus)return;gesture.current={x:e.clientX,y:e.clientY,camera};e.currentTarget.setPointerCapture(e.pointerId)};
 const move=(e:ReactPointerEvent<SVGSVGElement>)=>{if(drag){setDrag({...drag,x:e.clientX,y:e.clientY});return}const g=gesture.current;if(!g)return;const scale=camera.w/e.currentTarget.clientWidth;setCamera({...g.camera,x:Math.max(0,Math.min(WORLD.w-g.camera.w,g.camera.x-(e.clientX-g.x)*scale)),y:Math.max(0,Math.min(WORLD.h-g.camera.h,g.camera.y-(e.clientY-g.y)*scale))})};
 const up=(e:ReactPointerEvent<SVGSVGElement>)=>{gesture.current=null;if(!drag)return;const near=e.clientY>innerHeight-190&&e.clientX>innerWidth-190;if(near){update(drag.id,{state:'picked'});setFocus(undefined);setCamera(saved);if(picked.length===4)setTimeout(()=>{setPhase('discover');setStep(0)},650)}setDrag(undefined)};
 const wheel=(e:WheelEvent<SVGSVGElement>)=>{if(focus)return;e.preventDefault();const factor=e.deltaY>0?1.12:.88,nw=Math.max(520,Math.min(1800,camera.w*factor)),nh=nw*(innerHeight/innerWidth);setCamera(c=>({...c,x:Math.max(0,Math.min(WORLD.w-nw,c.x+(c.w-nw)/2)),y:Math.max(0,Math.min(WORLD.h-nh,c.y+(c.h-nh)/2)),w:nw,h:nh}))};
 const hear=(b:SoundBerry)=>{setPlaying(b.id);engine.trigger(b,false,()=>setPlaying(undefined))};
 const choose=(verb:SensoryVerb)=>{const b=picked[step];update(b.id,{sensoryVerb:verb});setTimeout(()=>step===4?setPhase('play'):setStep(s=>s+1),520)};
 const findStart=async()=>{engine.stopAll();await engine.context.resume();engine.play(0);setPhase('find')};
 if(phase==='discover')return <main className="discovery"><p className="chapter">Écoute ta cueillette.</p><div className="discover-berry"><Berry b={picked[step]} active={playing===picked[step]?.id} onClick={()=>hear(picked[step])}/><span>Touche la baie</span></div><h2>Ce son, ça te fait quoi ?</h2><div className="verb-corolla">{SENSORY_VERBS.map(v=><button key={v.id} aria-label={v.label} title={v.label} onClick={()=>choose(v.id)}><span>{v.emoji}</span><b>{v.label}</b></button>)}</div><div className="five-dots">{picked.map((b,i)=><i className={i<=step?'done':''} key={b.id}/>)}</div></main>;
 if(phase==='play')return <main className="play"><p className="chapter">Tes sons sont au bout de ton oreille.</p><div className="growth">{picked.map((b,i)=><i key={b.id} className={b.sensoryVerb} style={{'--i':i,'--c':verbById(b.sensoryVerb).primary} as React.CSSProperties}/>)}</div><div className="instrument" aria-label="Oreille instrument">{picked.map(b=><Berry key={b.id} b={b} active={playing===b.id} onClick={()=>hear(b)}/>)}</div><button className="find-cta" onClick={findStart}>RETROUVER MES SONS</button></main>;
 return <main className="bush" style={{'--energy':Math.min(1,analysis.globalRms*analysis.gain*3)} as React.CSSProperties}><svg className="bush-scene" viewBox={`${camera.x} ${camera.y} ${camera.w} ${camera.h}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onWheel={wheel} onClick={e=>{if(focus&&e.target===e.currentTarget)close()}}><defs><filter id="soft"><feGaussianBlur stdDeviation="2"/></filter><linearGradient id="branch"><stop stopColor="#48694e"/><stop offset="1" stopColor="#b0c184"/></linearGradient></defs><g className={focus?'dim':''}>{paths.map((d,i)=><g key={d}><path className="branch-shadow" d={d}/><path className="branch" d={d}/>{i<5&&<path className="vein" d={d}/>}</g>)}</g>{berries.map(b=><g key={b.id} transform={`translate(${b.position.x} ${b.position.y})`} className={`${b.state} ${focus&&focus!==b.id?'dim':''}`} onClick={e=>{e.stopPropagation();open(b)}}><line className="stem" y2="-42"/><Berry b={b} large={focus===b.id}/></g>)}</svg>{phase==='explore'&&tip&&<div className="instruction">Trouve 5 sons cachés.<small>Glisse pour explorer · pince pour t’approcher</small></div>}{phase==='find'&&<div className="instruction">Retrouve tes 5 sons dans le BuisSon.<small>Écoute… puis touche une baie dans l’oreille.</small></div>}{focus&&berry&&<div className="focus-help">Glisse la baie vers l’oreille<small>Touche autour pour revenir</small></div>}<Ear berries={picked} onBerry={phase==='find'?b=>{const ok=engine.time>=b.sourceStart-2&&engine.time<=b.sourceEnd+2;if(ok)update(b.id,{state:'seen'});}:undefined}/>{focus&&berry&&<button className="drag-berry" aria-label="Cueillir cette baie" style={drag?{left:drag.x,top:drag.y}:undefined} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag({id:berry.id,x:e.clientX,y:e.clientY})}}><Berry b={berry} large/></button>}</main>;
}

function Berry({b,large=false,active=false,onClick}:{b:SoundBerry;large?:boolean;active?:boolean;onClick?:()=>void}){const f=b.audioFeatures,r=large?58:22+f.rms*12;return <button className={`berry ${large?'large':''} ${active?'sounding':''} ${b.sensoryVerb??''}`} style={{'--r':`${r}px`,'--seed':b.visualSeed%8} as React.CSSProperties} onClick={onClick} aria-label={b.sensoryVerb?`Baie ${verbById(b.sensoryVerb).label}`:'Observer cette baie'}><i/><i/><i/>{large&&<svg viewBox="0 0 120 80"><path d={`M6 43 Q 20 ${25+f.low*25} 35 40 T65 ${25+f.high*30} T114 40`}/><path d={`M8 52 Q35 ${60-f.flux*35} 58 46 T112 52`}/></svg>}</button>}
function Ear({berries,onBerry}:{berries:SoundBerry[];onBerry?:(b:SoundBerry)=>void}){return <aside className="ear" aria-label={`${berries.length} baies cueillies`}><div className="ear-line"/>{Array.from({length:5},(_,i)=><button key={i} aria-label={berries[i]?'Baie cueillie':'Place vide'} onClick={()=>berries[i]&&onBerry?.(berries[i])} className={berries[i]?.state==='seen'?'found':''}>{berries[i]&&<Berry b={berries[i]}/>}</button>)}</aside>}
