import{useEffect,useRef,useState,type CSSProperties}from'react';
import type{AudioEngine}from'../audio/audioEngine';
import{SENSORY_VERBS,verbById,type AudioMoodSample,type SensoryVerb}from'../types/audiomood';
import{VJScene}from'../visual/VJScene';
export function MixView({samples,engine,onCustomize,onBack}:{samples:AudioMoodSample[];engine:AudioEngine;onCustomize:(id:string,verb:SensoryVerb)=>void;onBack:()=>void}){
 const[index,setIndex]=useState(()=>Math.max(0,samples.findIndex(s=>!s.sensoryVerb))),[active,setActive]=useState(new Set<string>()),[generated,setGenerated]=useState(samples.every(s=>s.sensoryVerb)),[verb,setVerb]=useState<SensoryVerb|undefined>(samples[index]?.sensoryVerb),timers=useRef<number[]>([]),hold=useRef<number|undefined>(undefined),sample=samples[index];
 const play=(s:AudioMoodSample,loop=false)=>{void engine.trigger(s,loop,()=>setActive(a=>{const n=new Set(a);n.delete(s.id);return n}));setActive(a=>new Set(a).add(s.id))};
 const validate=()=>{if(!sample||!verb)return;onCustomize(sample.id,verb);if(index<samples.length-1){const next=samples[index+1];setIndex(index+1);setVerb(next.sensoryVerb)}else setGenerated(true)};
 const playHaiku=()=>{timers.current.forEach(clearTimeout);engine.stopAll();setActive(new Set());samples.forEach((s,i)=>timers.current.push(window.setTimeout(()=>play(s),i*3900)))};
 const silence=()=>{timers.current.forEach(clearTimeout);engine.stopAll();setActive(new Set())};
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 if(generated)return <main className="haiku"><header><button onClick={onBack}>← TES SONS</button><div className="mini-logo">Audio<span>Mood</span></div><span>TON HAÏKU</span></header><section className="stage"><VJScene samples={samples} active={active}/><div className="haiku-title"><small>TON HAÏKU SONORE</small><h2>3 sons.<br/>3 sensations.<br/>Du silence.</h2><button onClick={playHaiku}>▶ FAIS-LE VIVRE</button></div></section><div className="haiku-notes">{samples.map((s,i)=>{const v=verbById(s.sensoryVerb);return <button key={s.id} style={{'--mood':v.primary}as CSSProperties} onPointerDown={()=>{hold.current=window.setTimeout(()=>play(s,true),420)}} onPointerUp={()=>{if(hold.current){clearTimeout(hold.current);hold.current=undefined;play(s)}}}><b>{i+1}</b><span>{v.emoji}</span><small>{v.label}</small></button>})}<button className="silence" onClick={silence}><b>○</b><span>○</span><small>SILENCE</small></button></div></main>;
 if(!sample)return null;
 const preview=verb?{...sample,sensoryVerb:verb}:sample;
 return <main className="feel-step"><header><button onClick={onBack}>← RETOUR</button><div className="mini-logo">Audio<span>Mood</span></div><span>{index+1} / 3</span></header><section className="sample-listen"><VJScene samples={[preview]} active={verb?new Set([sample.id]):new Set()}/><button className="big-play" onClick={()=>play(sample)}>▶</button><small>ÉCOUTE TON SON {index+1}</small><div className="pad-steps">{samples.map((_,i)=><i key={i} className={i===index?'current':i<index?'done':''}/>)}</div></section><section className="question"><h2>Ce son, ça te fait quoi ?</h2><div className="choice-moods">{SENSORY_VERBS.map(v=><button title={v.prompt} className={verb===v.id?'chosen':''} style={{'--mood':v.primary}as CSSProperties} key={v.id} onClick={()=>setVerb(v.id)}><span>{v.emoji}</span><b>{v.label}</b><small>{v.prompt}</small></button>)}</div><button className="validate" disabled={!verb} onClick={validate}>{index===2?'MON HAÏKU EST PRÊT':'SON SUIVANT'} →</button></section></main>
}
